# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dutis < Formula
  desc "A command-line tool to select default applications, based on duti (Fork with enhancements)"
  homepage "https://github.com/tobiashochguertel/dutis"
  version "0.3.0-fork"
  license "MIT"

  depends_on "git"
  depends_on "go"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/tobiashochguertel/dutis/releases/download/v0.3.0-fork/dutis_Darwin_x86_64.tar.gz"
    sha256 "b78107c2711b30d4b18a4e2488a78cec411adb9c76cb2d702c7fcb2d499f51d2"

    def install
      bin.install "dutis"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/tobiashochguertel/dutis/releases/download/v0.3.0-fork/dutis_Darwin_arm64.tar.gz"
    sha256 "2a38d651c0f34a6428c7bd1ca597215561c3582ff261a03d6db6849a35dd8907"

    def install
      bin.install "dutis"
    end
  end

  def caveats
    <<~EOS
      This is an enhanced fork of mrtkrcm/dutis with performance improvements and config management.
    EOS
  end

  test do
    system "#{bin}/dutis", "help"
  end
end
