# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dutis < Formula
  desc "A command-line tool to select default applications, based on duti (Fork with enhancements)"
  homepage "https://github.com/tobiashochguertel/dutis"
  version "0.2.1-fork"
  license "MIT"

  depends_on "git"
  depends_on "go"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/tobiashochguertel/dutis/releases/download/v0.2.1-fork/dutis_Darwin_x86_64.tar.gz"
    sha256 "0bcc9632ac2cd5e878484fca4d0b10cf7bc1bed5adecec78281335887e5de5e8"

    def install
      bin.install "dutis"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/tobiashochguertel/dutis/releases/download/v0.2.1-fork/dutis_Darwin_arm64.tar.gz"
    sha256 "806b5c23f4bc8e590120dc9fe1288ffd4c829615de302f1c4e965a018962d959"

    def install
      bin.install "dutis"
    end
  end

  def caveats
    <<~EOS
      This is an enhanced fork of mrtkrcm/dutis with performance improvements and config management.
    EOS
  end

  test do
    system "#{bin}/dutis", "help"
  end
end
