# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dutis < Formula
  desc "A command-line tool to select default applications, based on duti (Fork with enhancements)"
  homepage "https://github.com/tobiashochguertel/dutis"
  version "0.2.1-fork"
  license "MIT"

  depends_on "git"
  depends_on "go"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/tobiashochguertel/dutis/releases/download/v0.2.1-fork/dutis_Darwin_x86_64.tar.gz"
    sha256 "7e3c0e89f2231a00116c174fdf03b4545cf492d387c4c92c2a3a921d32a51544"

    def install
      bin.install "dutis"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/tobiashochguertel/dutis/releases/download/v0.2.1-fork/dutis_Darwin_arm64.tar.gz"
    sha256 "6437ec7443d2011ff8be53803e921d2f361b91dc548f39832acdf95c8c0aa1ec"

    def install
      bin.install "dutis"
    end
  end

  def caveats
    <<~EOS
      This is an enhanced fork of mrtkrcm/dutis with performance improvements and config management.
    EOS
  end

  test do
    system "#{bin}/dutis", "help"
  end
end
