# typed: false
# frozen_string_literal: true

# This file will be generated by GoReleaser.
class Dutis < Formula
  desc "A command-line tool to select default applications, based on duti (Fork with enhancements)"
  homepage "https://github.com/tobiashochguertel/dutis"
  version "0.1.0-fork"
  license "MIT"

  depends_on "git"
  depends_on "go"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tobiashochguertel/dutis/releases/download/v0.1.0-fork/dutis_Darwin_arm64.tar.gz"
      sha256 "TO_BE_GENERATED_BY_GORELEASER"

      def install
        bin.install "dutis"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tobiashochguertel/dutis/releases/download/v0.1.0-fork/dutis_Darwin_x86_64.tar.gz"
      sha256 "TO_BE_GENERATED_BY_GORELEASER"

      def install
        bin.install "dutis"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tobiashochguertel/dutis/releases/download/v0.1.0-fork/dutis_Linux_x86_64.tar.gz"
      sha256 "TO_BE_GENERATED_BY_GORELEASER"

      def install
        bin.install "dutis"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tobiashochguertel/dutis/releases/download/v0.1.0-fork/dutis_Linux_arm64.tar.gz"
      sha256 "TO_BE_GENERATED_BY_GORELEASER"

      def install
        bin.install "dutis"
      end
    end
  end

  test do
    system "#{bin}/dutis", "help"
  end
end
