name: Release

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  release:
    types: [created]

permissions: read-all

jobs:
  release:
      runs-on: macos-latest
      steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Create Git Tag
        run: |
          git tag v${{ github.run_number }}
          git push origin v${{ github.run_number }}
      - name: Set up GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
